macos_fix_torchlib:
	sudo xattr -r -d com.apple.quarantine libtorch/lib/

download_libtorch_macos:
	# TODO

download_libtorch_linux:
	# TODO

download_libtorch_windows:
	# TODO

prepare_ubuntu:
	sudo apt install nvidia-cuda-toolkit

prepare_macos:
	brew install libomp